### ISSUE TITLE
[Feature suggestion] Sticky wires and infiniwires

### ISSUE THREAD

**Issue by AbacusOperator** [mrp-v2/MoreWires#4]
Sticky wire (or infiniwire) is made from one piece of normal wire (or inifiniwire) and one slime ball. It is not washed away by water and can be waterlogged. Optional feature: it can also run up the walls and ceiling.

**Comment by mrp-v2** [comment]
Thanks for leaving a suggestion! Unfortunately, those features are outside the 'scope' of this mod. I intended this mod to just be about adding some colored redstone and special redstone that doesn't lose signal strength, so you're suggested features will not become a part of this mod.
With that said, I am considering making an addon mod that adds the water-related features you suggested. I am not sure if it would include having wires on the walls and ceiling, that might be too much work.

**Comment by AbacusOperator** [comment]
> Thanks for leaving a suggestion! Unfortunately, those features are outside the 'scope' of this mod

Well, my logic was that since mod is called 'More Wires' stuff in category 'more property variation for redstone wires' is in the mod's 'scope'. But understandable, thanks for answering anyway.

> With that said, I am considering making an addon mod that adds the water-related features you suggested.

This would be great.

**Comment by mrp-v2** [comment]
Development has paused while waiting for MinecraftForge/MinecraftForge#7677 to be merged.

**Comment by mrp-v2** [comment]
Now waiting for MinecraftForge/MinecraftForge#7750 to be merged.

**Comment by mrp-v2** [comment]
Development Teaser:
![2021-05-08_08 53 26](https://user-images.githubusercontent.com/25274244/117539957-de2aa480-afda-11eb-9686-6f6b74194b34.png)

**Comment by mrp-v2** [comment]
https://www.curseforge.com/minecraft/mc-mods/more-sticky-wires
